name: Check dnsmasq configuration
on: push

jobs:
  build:
    name: Check dnsmasq configuration
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: echo
          run: echo "::add-matcher::./.github/lint/dnsmasq.eslint"
        - name: Action
          uses: ./.github/dnsmasq

